# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='password',
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='first_app.User'),
        ),
    ]
